### ISSUE TITLE
Unclear about angle orientations

### ISSUE THREAD

**Issue by minglethepringle** [Endoman123/motion-profile-generator#11]
The example image shows that an angle specified at 90 degrees will turn clockwise to the right. However, when I'm generating my trajectory, I want it to turn 30 degrees to the left, so I specify -30. The behavior is as shown:

![image](https://user-images.githubusercontent.com/16504328/38470567-d142245c-3b32-11e8-835f-a37fe0cdd196.png)

This is not what I want, so I change the angle measurement to 30 degrees, and it works. However, this is just inconsistent with the example.

Furthermore, if I specify 90 degrees and -90 degrees, they're the same apparently. I would expect one to turn to the left and one to turn to the right.

![image](https://user-images.githubusercontent.com/16504328/38470585-0f1aec14-3b33-11e8-8bef-af8b6e626bfa.png)
![image](https://user-images.githubusercontent.com/16504328/38470586-170a2d7c-3b33-11e8-8878-bfffba5e02d3.png)

**Comment by sriharis123** [comment]
I believe this is an issue with the libraries that are used by this generator (Jaci's Pathfinder), and not the generator itself. I may be wrong.

**Comment by minglethepringle** [comment]
@sriharis123 I'm afraid that because of this issue, my trajectories are wrong :(

**Comment by Endoman123** [comment]
@minglethepringle I think the misconception is because of the second issue; the angle is actually measured counter-clockwise, until you get to ±90, ±180, ±270, ±360 or 0; they are (for some reason) the same angle. @sriharis123's point still stands in that this is a problem with the Pathfinder libraries and not the UI.

**Comment by minglethepringle** [comment]
@Endoman123 it displays correctly on the graph, but do you think the trajectories would be generated accurately, even with the "incorrect" angle?

**Comment by Endoman123** [comment]
@minglethepringle AFAIK it should be fine; from my own personal experience with using the Pathfinder library, it has not affected the path.

Best way to check is to generate a CSV and look through the trajectory points in some kind of table viewer

**Comment by minglethepringle** [comment]
@Endoman123 alrighty, thanks!

**Comment by JaciBrunning** [comment]
This is a bug due to how Pathfinder treats angles that sit in specific locations on a circle, depending on the slope angle between the waypoints. Basically, if you plot a straight line between two waypoints, the angle of either waypoint is calculated as an offset from this angle. This adds the constraint that you can't have a perpendicular exit angle, since this is `tan(90)` which is inf. This also means any angles over 90deg with respect to these two lines will not be signed. 

This is being fixed in V2

**Comment by minglethepringle** [comment]
@JacisNonsense Will my trajectories still be generated accurately, as shown by the generator?

**Comment by JaciBrunning** [comment]
What do you mean? The display in the generator is _the_ trajectory, they are one in the same

**Comment by minglethepringle** [comment]
@JacisNonsense Because I specified -90° instead of 90° because they displayed as the same; I don't want my trajectory to be shown pointing left and generated pointing right or something.

**Comment by JaciBrunning** [comment]
They are the same, there is no discrepancy between them - what the graph shows is what you'll get
